// One-time / re-runnable data-build script (not shipped to the browser).
// Merges CC-CEDICT (definitions) with the Complete HSK Vocabulary dataset
// (HSK levels 1-7) into two lean static JSON files consumed by the app:
//   src/data/dict.json      -> { "word": [{ t?, p, d:[...] }] }
//   src/data/hskWords.js    -> export default { "word": 1..7 }
//
// The dictionary includes all CC-CEDICT vocabulary and prioritizes standard
// real-word meanings over surname/abbreviation entries. Any HSK headwords missing in
// CC-CEDICT fall back to definitions and pinyin from the HSK dataset.
// Single characters appearing in HSK compounds derive their HSK level from
// the minimum level among compounds they belong to.
//
// Run with: npm run build:data
import { writeFileSync, readFileSync } from 'node:fs';
import { pinyin } from 'pinyin-pro';

const cedict = JSON.parse(readFileSync(new URL('../node_modules/cedict-json/cedict.json', import.meta.url)));

const HSK_URL =
  'https://raw.githubusercontent.com/drkameleon/complete-hsk-vocabulary/main/complete.min.json';

console.log('Fetching HSK level data...');
const hsk = await fetch(HSK_URL).then((res) => res.json());

const hskMap = new Map();
for (const entry of hsk) {
  if (entry.s) hskMap.set(entry.s, entry);
}

const levelOf = {};
for (const entry of hsk) {
  const nums = (entry.l || [])
    .map((code) => parseInt(code.slice(1), 10))
    .filter((n) => n >= 1 && n <= 7);
  if (!nums.length) continue;
  const best = Math.min(...nums);
  const word = entry.s;
  if (levelOf[word] === undefined || best < levelOf[word]) levelOf[word] = best;
}

// Derive HSK levels for single characters from any compound words they appear in
for (const [word, level] of Object.entries(levelOf)) {
  for (const char of word) {
    if (levelOf[char] === undefined || level < levelOf[char]) {
      levelOf[char] = level;
    }
  }
}

function isSurnameOrAbbr(str) {
  if (!str) return false;
  const s = str.trim();
  return /^surname\s+/i.test(s) || /^surname$/i.test(s) || /^abbr\.\s+for\s+/i.test(s);
}

function cleanEnglishList(engList) {
  const list = Array.isArray(engList) ? engList : [engList];
  return list.filter((d) => !isSurnameOrAbbr(d));
}

// Group CEDICT entries by simplified headword
const cedictByWord = new Map();
for (const e of cedict) {
  const word = e.simplified;
  if (!word) continue;
  if (!cedictByWord.has(word)) {
    cedictByWord.set(word, []);
  }
  cedictByWord.get(word).push(e);
}

const dict = {};

for (const [word, entries] of cedictByWord.entries()) {
  // Find best entry with real word definition (non-surname, non-abbr)
  let bestEntry = entries.find((e) => cleanEnglishList(e.english).length > 0);
  if (!bestEntry) bestEntry = entries[0];

  const cleaned = cleanEnglishList(bestEntry.english);
  const rawList = Array.isArray(bestEntry.english) ? bestEntry.english : [bestEntry.english];
  const sourceList = cleaned.length > 0 ? cleaned : rawList;

  // Filter out CL: (classifier) tags if other definitions exist
  const defsWithoutCL = sourceList.filter((d) => !/^CL:/i.test(d));
  const finalDefs = defsWithoutCL.length > 0 ? defsWithoutCL : sourceList;

  // Join top 2 definitions
  const definitionString = finalDefs.slice(0, 2).map((s) => s.trim()).filter(Boolean).join('; ');

  const sense = { p: bestEntry.pinyin, d: [definitionString] };
  if (bestEntry.traditional && bestEntry.traditional !== word) {
    sense.t = bestEntry.traditional;
  }

  dict[word] = [sense];
}

// Fallback: Populate definitions/pinyin/traditional for any HSK headwords missing from CC-CEDICT
let addedFromHskCount = 0;
for (const word of Object.keys(levelOf)) {
  if (!dict[word]) {
    const entry = hskMap.get(word);
    if (entry && entry.f && entry.f.length > 0) {
      const form = entry.f[0];
      const pinyinFormatted = pinyin(word, { toneType: 'num' });
      const meaning = form.m ? form.m.join('; ').trim() : '';
      const sense = { p: pinyinFormatted, d: [meaning] };
      if (form.t && form.t !== word) sense.t = form.t;
      dict[word] = [sense];
      addedFromHskCount++;
    }
  }
}

writeFileSync('src/data/dict.json', JSON.stringify(dict));
writeFileSync(
  'src/data/hskWords.js',
  `// Generated by scripts/build-data.mjs — do not edit manually.
export default ${JSON.stringify(levelOf, null, 2)};
`
);

console.log('dict entries:', Object.keys(dict).length);
console.log('hsk-leveled words:', Object.keys(levelOf).length);
console.log('added from HSK fallback:', addedFromHskCount);
